### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 1024mb** [nomoketo/ttml2srt#10]
After trying to convert from a ttml file to srt I got this message:

```
- Marking Time.español.srt"
  File "ttml2srt.py", line 190
    def format_timestamp(timestamp: timedelta):
                                  ^
SyntaxError: invalid syntax
```

Here is the file I'm trying to convert to srt:
[transcript.zip](https://github.com/codingcatgirl/ttml2srt/files/2704890/transcript.zip)
Thanks for any help.

**Comment by codingcatgirl** [comment]
Use the newest version of python 3.
