### ISSUE TITLE
Subtitles with <br> tags are ommited

### ISSUE THREAD

**Issue by xianwenchen** [nomoketo/ttml2srt#2]
Hi!

I found that style="center" is not recognized by the script. Could you have a look at the attached subtitle in ttml format and the converted subtitle in srt format? You can see that all lines with style="center" are omitted.

Could you also check whether style="right" is coded in the script, just in case?

Thank you!

Cheers,

Xianwen

[Katten_med_hatten-S02-E05.mp4.subtitle.zip](https://github.com/nomoketo/ttml2srt/files/890961/Katten_med_hatten-S02-E05.mp4.subtitle.zip)

**Comment by codingcatgirl** [comment]
Hi, srt does not support text alignment, so this is expected behaviour :)

**Comment by codingcatgirl** [comment]
Oh sorry, now i see… not the style is ignored, but the complete line. I will look into it later.

**Comment by xianwenchen** [comment]
Thank you!
