### ISSUE TITLE
ValueError: unknown time expression: 00:-11:-48.-340

### ISSUE THREAD

**Issue by xianwenchen** [nomoketo/ttml2srt#3]
Hi!

Thank you for fixing and improving the ttml2srt in the past! 

I am here to report a new bug.

While trying to convert the attached ttml, I got the following error:

> Traceback (most recent call last):
>   File "/home/chen/bin/ttml2srt.py", line 88, in <module>
>     parse_times(body)
>   File "/home/chen/bin/ttml2srt.py", line 86, in parse_times
>     parse_times(child, default_begin=begin)
>   File "/home/chen/bin/ttml2srt.py", line 86, in parse_times
>     parse_times(child, default_begin=begin)
>   File "/home/chen/bin/ttml2srt.py", line 75, in parse_times
>     dur = parse_time_expression(elem.attrib['dur'])
>   File "/home/chen/bin/ttml2srt.py", line 60, in parse_time_expression
>     raise ValueError('unknown time expression: %s' % expression)
> ValueError: unknown time expression: 00:-11:-48.-340

Could you have a look?

Have a nice Easter by the way!

**Comment by xianwenchen** [comment]
Here is the ttml file in zip archive!
[Katten_med_hatten-S02-E28.mp4.ttml.zip](https://github.com/nomoketo/ttml2srt/files/917565/Katten_med_hatten-S02-E28.mp4.ttml.zip)

**Comment by codingcatgirl** [comment]
Well, that's not a valid ttml file, see line 128:
> &lt;p begin="00:11:48.040" dur="00:-11:-48.-340" style="left"&gt;Nå må vi fylle opp tanken før vi går.&lt;br /&gt;Til den andre siden av bassenget!&lt;/p&gt;
A negative duration makes no sense and is not a valid time expression according to https://www.w3.org/TR/ttaf1-dfxp/#timing-value-timeExpression.

I would recommend removing or correcting this line.
