### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by svaningelgem** [nomoketo/ttml2srt#4]
> Traceback (most recent call last):
>   File "ttml2srt.py", line 8, in <module>
>     tree = ET.parse(filename)
>   File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1187, in parse
>     tree.parse(source, parser)
>   File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 598, in parse
>     self._root = parser._parse_whole(source)
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

Source file:
[textnld.txt](https://github.com/nomoketo/ttml2srt/files/1097254/textnld.txt)

Very likely because there is still binary content in there, in between of the XML...

**Comment by codingcatgirl** [comment]
Wenn, that is clearly not a valid XML file, so it's no surprise that pythons XML parser complains. It's also not a valid TTML file. Where is this from?

**Comment by svaningelgem** [comment]
This was part of a stream I got the other day. I don't know if you want to
interpret this as well? The data exists of several chunks it seems. 4 bytes
to denote the length (which includes this header). Then 4 bytes as a
keyword, and the rest the actual data.
If the keyword is 'mdat' the rest is the XML.
As it's a stream, this ttml is splitted among several downloads. I
implemented this conversion routine in around 15 lines in PHP ;).

Grtz,
Steven

**Comment by codingcatgirl** [comment]
This does not seem like this tool's job to fix. If you wrote a tool to convert this, shouldn't you be able to extract the correct xml file without those binary metadata?

**Comment by svaningelgem** [comment]
Yes I did. I was just trying to improve your tool.

Peace, out. :-)

**Comment by codingcatgirl** [comment]
ok :)
