### ISSUE TITLE
Italics and white space incorrectly stripped

### ISSUE THREAD

**Issue by jlick** [nomoketo/ttml2srt#6]
I have a ttml file I've tried converting with several utilities. Yours is working 99% correctly but there are some issues with italics that aren't being converted correctly:

This:

`<p begin="00:01:02.562" end="00:01:06.31"><span tts:fontStyle="italic">EXAMPLE</span> TEXT<br/>YET ANOTHER <span tts:fontStyle="italic">EXAMPLE</span> TEXT.</p>`

Is getting converted to this:

17
00:01:02,562 --> 00:01:06,310
EXAMPLETEXT
YET ANOTHEREXAMPLETEXT.

So there are two issues here:
1) This italics format isn't being detected correctly
2) White space is being trimmed which shouldn't be

I see that ttml2srt is supposed to handle italics but I couldn't figure out why it isn't handling this case. Even if that isn't corrected, the issue of essential white space being trimmed should be corrected so that words don't get smushed together.

**Comment by codingcatgirl** [comment]
Please supply the complete file if possible, so i can look into it properly. Thanks!

**Comment by jlick** [comment]
Here you go:

[example.zip](https://github.com/codingcatgirl/ttml2srt/files/2356908/example.zip)

**Comment by codingcatgirl** [comment]
Both issues should be fixed now. Let me know if you notice anything else!

**Comment by jlick** [comment]
Awesome. Confirmed both issues fixed. Many thanks.
