### ISSUE TITLE
Parsing Error on Python 3.7

### ISSUE THREAD

**Issue by WebFikirleri** [nomoketo/ttml2srt#7]
Here is the output

`M:\FlixGrab>"Q:\[QW]\ttml2srt\python.exe" "Q:\[QW]\ttml2srt\ttml2srt.py" "M:\FlixGrab\[S1.Ep2] Sherlock - The Blind Banker.Turkish.ttml"  > "M:\FlixGrab\[S1.Ep2] Sherlock - The Blind Banker.Turkish.srt"
Traceback (most recent call last):
  File "Q:\[QW]\ttml2srt\ttml2srt.py", line 88, in <module>
    parse_times(body)
  File "Q:\[QW]\ttml2srt\ttml2srt.py", line 86, in parse_times
    parse_times(child, default_begin=begin)
  File "Q:\[QW]\ttml2srt\ttml2srt.py", line 86, in parse_times
    parse_times(child, default_begin=begin)
  File "Q:\[QW]\ttml2srt\ttml2srt.py", line 64, in parse_times
    begin = parse_time_expression(elem.attrib['begin'], default_offset=default_begin)
  File "Q:\[QW]\ttml2srt\ttml2srt.py", line 49, in parse_time_expression
    raise NotImplementedError('Parsing time expressions by ticks is not supported!')
NotImplementedError: Parsing time expressions by ticks is not supported!`

**Comment by codingcatgirl** [comment]
This has nothing to do with python 3.7 but it's exactly what the error message says. This TTML file uses "ticks" as a time unit, which is not supported by ttml2srt because it would require information about the video stream.

**Comment by codingcatgirl** [comment]
My bad, it was a misunderstanding of the specification. ticks are supported now.
