### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by csrednicki** [nomoketo/ttml2srt#9]
Hi @codingcatgirl, there is a problem with special characters in converted files. In some situations the converter can't handle national characters and then an error occurs:

`File "d:\GIT\ttml2srt\ttml2srt.py", line 202, in <module>
    print(content)
  File "C:\Users\csrednicki\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 13: character maps to <undefined>`

The problematic line is:

`<p begin="8942266666t" end="8959283666t" xml:id="subtitle209">To pewnie déjà vu.</p>`

I came across this error also when converting another file. In the second case it was "\xe8". Line was:

`<p begin="15572223332t" end="15607925666t" xml:id="subtitle411">oraz „La donna è mobile"<br/>z <span style="normal_1">Rigoletto </span>Verdiego.</p>`

[I have attached the problematic files mentioned above.](https://github.com/codingcatgirl/ttml2srt/files/2433604/problematic-files.zip)

**Comment by csrednicki** [comment]
Another problematic word is: 

> Señor

**Comment by codingcatgirl** [comment]
Works for me with both of those files. But i'm on Linux, and you apparently are not.

This is a Windows-related problem because Windows is too big of a piece of shit for unicode.

You can find information on how to solve this here: https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console

**Comment by csrednicki** [comment]
Basically, for windows you have to enter this command before running ttml2srt:
`chcp 65001 & set PYTHONIOENCODING=utf-8`

**Comment by codingcatgirl** [comment]
Thanks, will point people to this when someone ask for this again! 

(Also, is it possible that with the newest versions of python this shouldn't happen? I really can't imagine that this is the state of things in 2018)
